name: uoc20211pec2
channels:
  - defaults
dependencies:
  - scikit-learn=0.24.1
  - python=3.9.1
  - seaborn=0.11.1
  - matplotlib=3.3.4
  - jupyter=1.0.0
  - numpy=1.19.2
  - pandas=1.2.2
  - scipy=1.6.2
  - pip=21.2.4
  - pip:
    - umap-learn==0.5.1
    - smopy==0.0.7
