---
title: 'Mineria de dades: PRA2 - Modelat d''un joc de dades'
author: "Autor: Nom estudiant"
date: "Novembre 2019"
output:
  html_document:
    highlight: default
    number_sections: yes
    theme: cosmo
    toc: yes
    toc_depth: 2
    includes:
      in_header: 05.584-PEC-header.html
  word_document: default
  pdf_document:
    highlight: zenburn
    toc: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
******
# Introducció
******
## Presentació
Aquesta pràctica cobreix de forma transversal la assignatura.

Les Pràctiques 1 i 2 de la assignatura es plantegen d'una forma conjunta de manera que la Pràctica 2 serà continuació de la 1.

L'objectiu global de les dues pràctiques consisteix en seleccionar un o diversos jocs de dades, realitzar les tasques de preparació i anàlisi exploratòria amb l'objectiu de disposar de dades llestos per aplicar algoritmes de clustering, associació i classificació.


******
# Generació de regles a partir d'arbres de decisió
******

******
# Model **no supervisat** basat en el concepte de **distància**
******

******
# Model **no supervisat** basat en una **mètrica diferent**
******

## Comparació de resultats


******
# **Model supervisat** sense haver aplicat prèviament **PCA/SVD**
******

******
# **Model supervisat** havent aplicat prèviament **PCA/SVD**
******

******
# Hi ha hagut millora en capacitat predictiva, després d'aplicar PCA/SVD? A què creus que és degut?
******

******
# Rúbrica
******
* 15%. Es generen regles i es comenten i interpreten les més significatives. A més es genera matriu de confusió per mesurar la capacitat predictiva de l'algoritme.  
* 15%. Es genera model no supervisat, es mostren i comenten mesures de qualitat del model generat i es comenten les conclusions aix? com la descripci? dels grups resultants.  
* 20%. Es genera model no supervisat amb mètrica de distància diferent a l'anterior. Es mostren i comenten mesures de qualitat del model generat i es comenten les conclusions. A més es comparen els dos models no supervisats amb mètriques de distància diferent aix? com la descripci? dels grups resultants.  
* 15%. Es genera un model supervisat sense PCA/SVD previ, es mostren i comenten mesures de qualitat del model generat i es comenta extensament el coneixement extret del model.  
* 15%. Es genera un model supervisat amb PCA/SVD previ, es mostren i comenten mesures de qualitat del model generat i es comenta extensament el coneixement extret del model. Es valorar? l'extracci? de coneixement del model generat.  
* 20%. Es compara la capacitat predictiva dels dos models supervisats i es comenta la diferència de rendiment en base a l'efecte PCA/SVD.  

