name: uoc20211pec4
channels:
  - defaults
dependencies:
  - scikit-learn=0.24.1
  - python=3.9.1
  - seaborn=0.11.1
  - matplotlib=3.3.4
  - jupyter=1.0.0
  - numpy=1.19.2
  - pandas=1.2.2
  - pydotplus=2.0.2
  - statsmodels=0.12.2
